///----------------------------------------------------------------------------
///	Nomis Seismograph, Inc.
///	Copyright 2003-2014, All Rights Reserved
///
///	Author: Jeremy Peterson
///----------------------------------------------------------------------------

///----------------------------------------------------------------------------
///	Includes
///----------------------------------------------------------------------------
#include "TextTypes.h"

///----------------------------------------------------------------------------
///	Defines
///----------------------------------------------------------------------------

///----------------------------------------------------------------------------
///	Externs
///----------------------------------------------------------------------------

///----------------------------------------------------------------------------
///	Local Scope Globals
///----------------------------------------------------------------------------
char englishLanguageTable[] = {
"A WEIGHTING\0A WEIGHTING OPTION\0A/D CALIBRATED OK\0ACTIVE DATE PERIOD\0ACTIVE TIME PERIOD\0AFTER EVERY 24 HR\0"\
"AFTER EVERY 48 HR\0AFTER EVERY 72 HR\0AIR\0AIR CHANNEL SCALE\0ALARM 1\0ALARM 1 AIR LEVEL\0ALARM 1 SEISMIC LVL\0"\
"ALARM 1 TIME\0ALARM 2\0ALARM 2 AIR LEVEL\0ALARM 2 SEISMIC LVL\0ALARM 2 TIME\0ALARM OUTPUT MODE\0ALL RIGHTS RESERVED\0"\
"ARE YOU DONE WITH CAL SETUP?\0ATTEMPTING TO HANDLE PARTIAL EVENT ERROR.\0AUTO CALIBRATION\0AUTO MONITOR\0"\
"AUTO MONITOR AFTER\0BAR GRAPH\0BAR INTERVAL\0BAR DISPLAY RESULT\0BARGRAPH ABORTED\0BARGRAPH MODE\0BARS\0BATT VOLTAGE\0"\
"BATTERY\0BATTERY VOLTAGE\0BOTH\0CAL DATE STORED.\0CAL SETUP\0CALIBRATING\0CALIBRATION\0CALIBRATION CHECK\0CALIBRATION DATE\0"\
"CALIBRATION DATE NOT SET.\0CALIBRATION GRAPH\0CALIBRATION PULSE\0CANCEL TIMER MODE?\0CLIENT\0COMBO\0COMBO MODE\0"\
"COMBO MODE NOT IMPLEMENTED.\0COMMENTS\0COMPANY\0CONFIG & OPTIONS\0CONFIG/OPTIONS MENU\0CONFIRM\0COPIES\0COPY\0"\
"CURRENTLY NOT IMPLEMENTED.\0DAILY (EVERY DAY)\0DAILY (WEEKDAYS)\0DARK\0DARKER\0DATE\0DATE/TIME\0DAY-MONTH-YEAR\0DEFAULT\0"\
"DEFAULT (BAR)\0DEFAULT (COMBO)\0DEFAULT (SELF TRG)\0DISABLED\0DISABLING TIMER MODE.\0DISCOVERED A BROKEN EVENT LINK.\0"\
"DISTANCE TO SOURCE\0DO NOT TURN THE UNIT OFF UNTIL THE OPERATION IS COMPLETE.\0DO YOU WANT TO ENTER MANUAL TRIGGER MODE?\0"\
"DO YOU WANT TO LEAVE CAL SETUP MODE?\0DO YOU WANT TO LEAVE MONITOR MODE?\0DO YOU WANT TO SAVE THE CAL DATE?\0EDIT\0EMPTY\0"\
"ENABLED\0ERASE COMPLETE.\0ERASE EVENTS\0ERASE MEMORY\0ERASE OPERATION IN PROGRESS.\0ERASE SETTINGS\0ERROR\0ESC HIT\0EVENT\0"\
"EVENT NUMBER ZEROING COMPLETE.\0EVENT SUMMARY\0FACTORY SETUP COMPLETE.\0FACTORY SETUP DATA COULD NOT BE FOUND.\0FAILED\0"\
"FEET\0FREQUENCY\0FREQUENCY PLOT\0FRQ\0FULL\0GRAPHICAL RECORD\0HELP INFO MENU\0HELP INFORMATION\0HELP MENU\0HOUR\0HOURS\0HR\0"\
"HZ\0INCHES\0INCLUDED\0INSTRUMENT\0JOB NUMBER\0JOB PEAK RESULTS\0JOB VECTOR SUM RESULTS\0LANGUAGE\0LAST SETUP\0"\
"LCD CONTRAST\0LIGHT\0LIGHTER\0LINEAR\0LIST OF SUMMARIES\0LOCATION\0LOW\0MILLIMETERS\0MIC A\0MIC B\0MINUTE\0MINUTES\0MMPS/DIV\0"\
"MONITOR\0MONITOR BARGRAPH\0MONITORING\0MONTHLY\0NAME\0NEXT EVENT STORAGE LOCATION NOT EMPTY.\0NO\0NO AUTO CAL\0"\
"NO AUTO MONITOR\0NO STORED EVENTS FOUND.\0NOMIS MAIN MENU\0NOT INCLUDED\0NOTES\0OFF\0ON\0ONE TIME\0OPERATOR\0"\
"OVERWRITE SETTINGS\0PARTIAL RESULTS\0PASSED\0PEAK\0PEAK AIR\0PLEASE BE PATIENT.\0"\
"PLEASE CONSIDER ERASING THE FLASH TO FIX PROBLEM.\0PLEASE POWER OFF UNIT.\0PLEASE PRESS ENTER.\0PLOT STANDARD\0"\
"POWERING UNIT OFF NOW.\0PRINT GRAPH\0PRINTER\0PRINTER ON\0PRINTING STOPPED\0PRINTOUT\0"\
"PROCEED WITHOUT SETTING DATE AND TIME?\0PROCESSING\0RAD\0RADIAL\0RAM SUMMARY TABLE IS UNINITIALIZED.\0"\
"RECORD TIME\0REPORT DISPLACEMENT\0RESULTS\0SAMPLE RATE\0SAVE CHANGES\0SAVE SETUP\0SAVED SETTINGS\0"\
"SCANNING STORAGE FOR VALID EVENTS.\0SEC\0SECOND\0SECONDS\0SEIS TRIG\0SEIS. LOCATION\0SEISMIC\0SEISMIC TRIGGER\0SELECT\0"\
"SELF TRIGGER\0SENSOR A\0SENSOR B\0SENSOR CHECK\0SENSOR GAIN/TYPE\0SENSOR GAIN/TYPE NOT SET.\0SENSOR TYPE\0SERIAL NUMBER\0"\
"SERIAL NUMBER NOT SET.\0SETTINGS WILL NOT BE LOADED.\0SOFTWARE VER\0SOUND\0AIR TRIG\0AIR TRIGGER\0SPANISH\0START DATE\0"\
"START TIME\0STATUS\0STOP DATE\0STOP PRINTING\0STOP TIME\0SUCCESS\0EVENT SUMMARIES\0SUMMARY INTERVAL\0"\
"SUMMARY INTERVAL RESULTS\0TESTING\0THIS FEATURE IS NOT CURRENTLY AVAILABLE.\0TIME\0TIMER FREQUENCY\0TIMER MODE\0"\
"TIMER MODE DISABLED.\0TIMER MODE NOW ACTIVE.\0TIMER MODE SETUP NOT COMPLETED.\0TIMER SETTINGS INVALID.\0TRAN\0TRANSVERSE\0"\
"UNIT IS IN TIMER MODE.\0UNITS OF MEASURE\0USBM/OSMRE REPORT\0VECTOR SUM\0VERIFY\0VERT\0VERTICAL\0VOLTS\0WARNING\0"\
"WAVEFORM MODE\0WEEKLY\0WEIGHT PER DELAY\0YES\0YOU HAVE ENTERED THE FACTORY SETUP.\0ZERO EVENT NUMBER\0ZEROING SENSORS\0"\
"OK\0CANCEL\0MAX\0CHARS\0RANGE\0ENGLISH\0ITALIAN\0FRENCH\0BRITISH\0DIN 4150\0US BOM\0X1 (20 IPS)\0X2 (10 IPS)\0X4 (5 IPS)\0"\
"X8 (2.5 IPS)\0BAR\0SELF TRG\0END\0REALLY ERASE ALL EVENTS?\0MODEM SETUP\0MODEM INIT\0MODEM DIAL\0MODEM RESET\0SENSITIVITY\0"\
"HIGH\0UNLOCK CODE\0ACC (793L)\0GERMAN\0BAUD RATE\0POWER UNIT OFF EARLY?\0NAME ALREADY USED\0DELETE SAVED SETUP?\0"\
"NAME MUST HAVE AT LEAST ONE CHARACTER\0BAR SCALE\0REPORT MILLIBARS\0LCD TIMEOUT\0IMPULSE RESULTS\0LCD IMPULSE TIME\0"\
"PRINT MONITOR LOG\0MONITOR LOG\0EVENTS RECORDED\0EVENT NUMBERS\0CANCEL ALL PRINT JOBS?\0CAL SUMMARY\0MODEM RETRY\0"\
"MODEM RETRY TIME\0FLASH WRAPPING\0FLASH STATS\0AUTO DIAL INFO\0PEAK DISPLACEMENT\0WAVEFORM AUTO CAL\0START OF WAVEFORM\0"\
"CALIBRATED ON\0VIEW MONITOR LOG\0PRINT IN MONITOR\0LOG RESULTS\0MONITOR LOG RESULTS\0PRINT MONITOR LOG ENTRY?\0"\
"PRINTER DISABLED\0PRINTING\0BARGRAPH REPORT\0NORMAL FORMAT\0SHORT FORMAT\0REPORT PEAK ACC\0PEAK ACCELERATION\0"\
"EVENT #s\0START OF LOG\0END OF LOG\0USED\0FREE\0EVENT DATA\0WRAPPED\0FLASH USAGE STATS\0SPACE REMAINING (CURR. SETTINGS)\0"\
"BEFORE OVERWRITE (CURR. SETTINGS)\0WAVEFORMS\0BAR HOURS\0LAST DL EVT\0LAST REC\0LAST CONNECT\0AUTO DIALOUT INFO\0"\
"UNITS OF AIR\0DECIBEL\0MILLIBAR\0 115200 BAUD RATE\0BIT ACCURACY\0BIT\0HOURLY\0RECALIBRATE\0ON TEMP. CHANGE\0PRETRIGGER SIZE\0"\
"QUARTER SECOND\0HALF SECOND\0FULL SECOND\0POWER SAVINGS\0NONE\0MINIMUM\0MOST\0ANALOG CHAN CONFIG\0CHAN R&V SCHEMATIC\0"\
"CHAN R&V SWAPPED\0NORMAL (DEFAULT)\0NORM & NO USB\0NORM & NO USB/CRAFT\0SAVE COMPRESS DATA\0YES (FASTER DL)\0"\
"FILE SYSTEM BUSY DURING\0ERROR TRYING TO ACCESS\0SUMMARY LIST\0INITIALIZING SUMMARY LIST WITH STORED EVENT INFO\0FILE NOT FOUND\0"\
"FILE CORRUPT\0UNABLE TO DELETE\0REMOVING\0UNABLE TO ACCESS\0DIR\0DELETE EVENTS\0REMOVED\0EVENTS\0FAILED TO INIT SD CARD\0"\
"FAILED TO MOUNT SD CARD\0FAILED TO SELECT SD CARD DRIVE\0SD CARD IS NOT PRESENT\0CALCULATING EVENT STORAGE SPACE FREE\0"\
"INITIALIZING MONITOR LOG WITH SAVED ENTRIES\0PLEASE CHARGE BATTERY\0USB THUMB DRIVE\0USB DEVICE CABLE WAS REMOVED\0"\
"USB HOST OTG CABLE WAS REMOVED\0DISCONNECTED\0DISCOVERED\0USB DOWNLOAD\0SYNC EVENTS TO USB THUMB DRIVE?\0SYNC IN PROGRESS\0"\
"SYNC SUCCESSFUL\0TOTAL EVENTS\0NEW\0EXISTING\0SYNC ENCOUNTERED AN ERROR\0PLEASE REMOVE THUMB DRIVE TO CONSERVE POWER\0"\
"USB DEVICE STATUS\0USB TO PC CABLE WAS CONNECTED\0USB TO PC CABLE WAS DISCONNECTED\0USB HOST STATUS\0USB DEVICE WAS CONNECTED\0"\
"USB OTG HOST CABLE WAS CONNECTED\0USB STATUS\0USB CONNECTION DISABLED FOR MONITORING\0USB CONNECTION DISABLED FOR FILE OPERATION\0"\
"USB DEVICE WAS REMOVED\0APP LOADER\0STARTING APP LOADER\0FLASH MEMORY IS FULL\0WRAPPING\0UNAVAILABLE\0STOPPED\0"\
"CLOSING MONITOR SESSION\0PERFORMING CALIBRATION\0BEING SAVED\0EVENT COMPLETE\0WAVEFORM\0COMBO WAVEFORM\0COMBO BARGRAPH\0"\
"MAY TAKE TIME\0SYNC PROGRESS\0EXISTS\0SYNCING\0ACOUSTIC\0TYPE\0STANDARD\0SMART SENSOR\0NOT FOUND\0START CALIBRATION DIAGNOSTICS?\0"\
"ERASE FACTORY SETUP?\0UNSUPPORTED DEVICE\0PLEASE REMOVE IMMEDIATELY BEFORE SELECTING OK\0UNIT SET FOR EXTERNAL TRIGGER\0"\
"SET TO NO TRIGGER\0PLEASE CHANGE\0SEISMIC OR AIR TRIGGER\0FOR HOURLY MODE THE HOURS AND MINUTES FIELDS ARE INDEPENDENT\0"\
"TIMER MODE HOURLY\0HOURS ARE ACTIVE HOURS MINS ARE ACTIVE MIN RANGE EACH HOUR\0FIRMWARE\0MODEM SYNC FAILED\0CRAFT SERIAL ERROR\0"\
"SENSOR CALIBRATION\0DISPLAY SUCCESSIVE SAMPLES\0CHANNEL NOISE PERCENTAGES\0DISPLAY CALIBRATED\0DISPLAY NOT CALIBRATED\0ZERO\0"\
"MIN MAX AVG\0CONNECT USB CABLE\0COPY TO SYSTEM DIR\0REMOVE CABLE WHEN DONE\0MENU ACTIVATION\0SERIAL ACTIVATION\0INITIALIZING\0"\
"EXTERNAL TRIGGER\0RS232 POWER SAVINGS\0BOTH TRIGGERS SET TO NO AND EXTERNAL TRIGGER DISABLED\0NO TRIGGER SOURCE SELECTED\0"\
"ALARM TESTING\0CHAN VERIFICATION\0HARDWARE ID\0REV 8 NORMAL\0REV 8 WITH GPS MOD\0REV 8 WITH USART\0SYNC FILE EXISTS\0"\
"SKIP\0REPLACE\0DUPLICATE\0SKIP (ALL)\0REPLACE (ALL)\0DUPLICATE (ALL)\0USB SYNC MODE\0PROMPT (CONFLICT)\0TOTAL FILES\0FILE\0"\
"FILES\0REPLACED\0DUPLICATED\0SKIPPED\0SENSOR WARMING UP FROM COLD START\0FORCED POWER OFF\0GPS LOCATION\0GPS LOCATION FIX\0"\
"GPS MODULE NOT INCLUDED\0EXCEPTION REPORT EXISTS DUE TO ERROR\0PLEASE CONTACT SUPPORT\0RESTORE FACTORY SETUP FROM BACKUP?\0"\
"ALSO ERASE THE REST OF THE EEPROM?\0ERASE FACTORY SETUP SHADOW COPY?\0ERASE ALL NON ESSENTIAL SYSTEM FILES?\0"\
"ACQUIRING SATELLITE SIGNALS\0CONTINUING ACQUISITION\0TIMED OUT\0SEISMIC GAIN/TYPE\0ACOUSTIC GAIN/TYPE\0MIC 148 DB\0MIC 160 DB\0"\
"CYCLE END TIME 24HR\0CHK SUMMARY FILE\0COMPARING EVENTS TO SUMMARY LIST...\0FOUND\0MERGE\0VALID EVENTS\0INVALID EVENTS\0"\
"MATCH SERIAL\0WRONG SERIAL\0NOT IN SUMMARY\0TO SUMMARY?\0SUMMARY FILE MATCHES EVENT STORAGE\0NO STRAY EVENTS\0"\
"24HR CYCLE WILL NOW OCCUR AT\0MIDNIGHT\0BAR DATA TO STORE\0A+RVT MAX\0A+R+V+T MAX\0A+R+V+T MAX&FREQ\0X05 (40 IPS)\0X025 (80 IPS)\0"\
"LEGACY DQM LIMIT\0STORED EVENTS CAP\0MAX EVTS TO KEEP\0ABOVE EVT CAP\0OLDEST FIRST\0STORED EVTS MORE THAN MAX\0"\
"DELETE OLD EVTS NOW?\0SENSOR CAL PULSE\0BAR LIVE MONITOR\0SEISMIC TRIG TYPE\0VARIABLE (USBM/OSM)\0VIBRATION STANDARD\0"\
"USBM 8507 DRYWALL\0USBM 8507 PLASTER\0OSM REGULATIONS\0REMOTE CONTROL\0BLIND SEND\0VARIABLE UNABLE TO SAMPLE AT 16K, SETTING TO 8K\0"\
"CUSTOM CURVE\0STEP THRESHOLD\0STEP LIMITING\0FREQ ALGORITHM\0HALF WAVE APPROX\0FULL WAVE COUNT\0DIAL OUT TYPE\0"\
"DIAL OUT CYCLE TIME\0EVTS/CFG/STATUS\0EVENTS ONLY\0GPS POWER\0NORMAL (SAVE POWER)\0ALWAYS ON/ACQUIRING\0UTC ZONE OFFSET\0"\
"ADAPTIVE SAMPLING\0SAMPLING METHOD\0FIXED (NORMAL)\0ADAPTIVE (SAVE BATT)\0SHOW OPTION IN SETUP\0HIDE OPTION/DISABLE\0"\
"MIC 5 PSI\0MIC 10 PSI\0PSI\0% OF LIMIT TRIGGER\0NORMAL\0\0"
};
